name: 'Validate Metrics'
description: |
  Runs a PromQL query on Grafana Cloud.
  Returns success (return code 0) if the query has a result.
  Returns failure if the result is empty (return code 1).
inputs:
  system:
    description: 'System is used to log in to Vault using correct role.'
    required: true
  environment:
    description: 'Environment is used to find correct vault instance.'
    required: true
  query:
    description: 'PromQL query string.'
    required: true
  checkout:
    description: 'If `true`, the action will check out the repository. If `false`, the action will assume the repository has already been checked out.'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - run: |
        # Explicit checks for required inputs, due to https://github.com/actions/runner/issues/1070
        [[ "$SYSTEM" ]] || { echo "Parameter 'system' is required, but is empty." ; exit 1; }
        [[ "$ENVIRONMENT" ]] || { echo "Parameter 'environment' is required, but is empty." ; exit 1; }
        [[ "$QUERY" ]] || { echo "Parameter 'query' is required, but is empty." ; exit 1; }
      shell: bash
      env:
        SYSTEM: ${{ inputs.system }}
        ENVIRONMENT: ${{ inputs.environment }}
        QUERY: ${{ inputs.query }}

    - name: Checkout repository
      if: ${{ inputs.checkout == 'true' }}
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

    - name: Login Vault and export token
      uses: 3lvia/core-github-actions-templates/vault@trunk
      with:
        system: ${{ inputs.system }}
        environment: ${{ inputs.environment }}
        exportToken: 'true'

    - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: '3.14'

    - name: Run PromQL query
      shell: bash
      run: |
        pip install -r "$GITHUB_ACTION_PATH/requirements.txt"
        python "$GITHUB_ACTION_PATH/validate_metrics.py" --query "$QUERY"
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
        QUERY: ${{ inputs.query }}
