name: 'Validate Metrics'
description: |
  Runs a PromQL query on Grafana Cloud.
  Returns success (return code 0) if the query has a result.
  Returns failure if the result is empty (return code 1).
inputs:
  system:
    description: 'System is used to log in to Vault using correct role.'
    required: true
  environment:
    description: 'Environment is used to find correct vault instance.'
    required: true
  query:
    description: 'PromQL query string.'
    required: true
  checkout:
    description: 'If `true`, the action will check out the repository. If `false`, the action will assume the repository has already been checked out.'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - run: |
        # Explicit checks for required inputs, due to https://github.com/actions/runner/issues/1070
        [[ "${{ inputs.system }}" ]] || { echo "system input is empty" ; exit 1; }
        [[ "${{ inputs.environment }}" ]] || { echo "environment input is empty" ; exit 1; }
        [[ "${{ inputs.query }}" ]] || { echo "query input is empty" ; exit 1; }
      shell: bash

    - name: Checkout repository
      if: ${{ inputs.checkout == 'true' }}
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

    - name: Login Vault and export token
      uses: 3lvia/core-github-actions-templates/vault@trunk
      with:
        system: ${{ inputs.system }}
        environment: ${{ inputs.environment }}
        exportToken: 'true'

    - name: Run PromQL query
      shell: bash
      run: |
        pip install -r '${{ github.action_path }}/requirements.txt'
        python '${{ github.action_path }}/validate_metrics.py' --query '${{ inputs.query }}'
