name: 'Terraform format check'
description: 'Uses the built-in formatter from the Terraform CLI to check the format of Terraform code.'
inputs:
  path:
    description: 'Path to process.'
    required: false
    default: '.'
  checkout:
    description: 'If `true`, the action will check out the repository. If `false`, the action will assume the repository has already been checked out.'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      if: ${{ inputs.checkout == 'true' }}
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Check formatting
      shell: bash
      run: terraform fmt -check -recursive ${{ inputs.path }}
