name: 'Terraform format check'
description: 'Uses the built-in formatter from the Terraform CLI to check the format of Terraform code.'
inputs:
  path:
    description: 'Path to process.'
    required: false
    default: '.'
  checkout:
    description: 'If `true`, the action will check out the repository. If `false`, the action will assume the repository has already been checked out.'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      if: ${{ inputs.checkout == 'true' }}
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1

    - name: Check formatting
      shell: bash
      run: terraform fmt -check -recursive ${{ inputs.path }}
