name: 'Vulnerabilities Slack Alert'
description: |
  Fetches vulnerabilities from the GitHub Security Advisory API and sends a message to a Slack channel with a list of new vulnerabilities from the past week.
inputs:
  slack-channel:
    description: 'Slack channel to send message to. The app "Github Workflow Notifications" must be added to the channel.'
    required: true
  slack-api-token:
    description: |
      Slack API token. Within the Elvia organization, you can use GitHub organization secret `SLACK_API_TOKEN`.

      If no input is provided, the action will attempt to read the token from Elvia's Vault instance.
      Reading the token from Vault is only possible if the repository you are running this action from has been added to [github-repositories-terraform](https://github.com/3lvia/github-repositories-terraform),
      and you are running inside the GitHub Actions environments `dev`, `test` or `prod`.
    required: false

runs:
  using: 'composite'
  steps:
    - name: Fetch code scanning results
      id: fetch-results
      shell: bash
      run: |
        results=$(curl -v -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/code-scanning/alerts")

        if [ $? -ne 0 ]; then
          echo "Failed to fetch code scanning results"
          exit 1
        fi
        echo "$results" > results.json

        new_vulnerabilities=$(jq '[.[] | select((.created_at > "'$(date -d '1 week ago' --utc +%Y-%m-%dT%H:%M:%SZ)'" or .updated_at > "'$(date -d '1 week ago' --utc +%Y-%m-%dT%H:%M:%SZ)'") and .state == "open")]' results.json)
        echo "$new_vulnerabilities" > new_vulnerabilities.json

    - name: Construct Slack message
      id: construct-slack-message
      shell: bash
      run: |
        results="$(cat new_vulnerabilities.json | jq -c .)"
        if [ "$results" != '[]' ]; then
          echo "Vulnerabilities have been found during code scanning."
          echo "Code Scanning Vulnerabilities:"
          echo "$results"
          message="*:warning: Vulnerabilities discovered during code scanning.* \n*Code Scanning Vulnerabilities:*"

          vulnerabilities=$(jq -c '.[] | {code: (.rule.tags[] | select(startswith("external/cwe/"))), date: .created_at, severity: .rule.security_severity_level, url: .html_url}' new_vulnerabilities.json)
          for vulnerability in $vulnerabilities; do
            code=$(echo $vulnerability | jq -r '.code')
            date=$(echo $vulnerability | jq -r '.date' | sed 's/T/ /' | sed 's/Z//')
            severity=$(echo $vulnerability | jq -r '.severity')
            url=$(echo $vulnerability | jq -r '.url')
            message="$message \n\n*Code:* $code \n*Date:* $date \n*Severity:* $severity \n*URL:* $url"
          done
        else
          message="*:white_check_mark: No new vulnerabilities have been found.*"
        fi
        echo "message=$message" >> $GITHUB_OUTPUT

    - name: Send Slack Message
      uses: 3lvia/core-github-actions-templates/slack-message@trunk
      with:
        message: ${{ steps.construct-slack-message.outputs.message }}
        slack-api-token: ${{ inputs.slack-api-token }}
        slack-channel: ${{ inputs.slack-channel }}
