name: 'Vulnerabilities Slack Alert'
description: |
  Fetches vulnerabilities from the GitHub Security Advisory API and sends a message to a Slack channel with a list of new vulnerabilities from the past week.
inputs:
  slack-channel:
    description: 'Slack channel to send message to. The app "Github Workflow Notifications" must be added to the channel.'
    required: true
  slack-api-token:
    description: |
      Slack API token. Within the Elvia organization, you can use GitHub organization secret `SLACK_API_TOKEN`.
    required: true
  github-token:
    description: |
      'GitHub token is used to authenticate on behalf of the GitHub Actions workflow and for interacting with the GitHub API. You can use the GitHub secret `GITHUB_TOKEN`.'
    required: true
  sort-by-newest:
    description: |
      'Sorts vulnerabilities by newest first. Set to `true` to have the vulnerabilities shown in order with newest first. By default the list is grouped by severity and then sorted by date created.'
    required: false
    default: 'false'
  max-alerts:
    description: 'Maximum number of vulnerabilities to show in the Slack alert. By default, the top 3 most severe vulnerabilities are shown.'
    required: false
    default: '3'

runs:
  using: 'composite'
  steps:
    - name: Fetch code scanning results
      id: fetch-results
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        SORT_BY_NEWEST: ${{ inputs.sort-by-newest }}
      run: |
        results=$(curl -v -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/${{ github.repository }}/code-scanning/alerts")

        if [ $? -ne 0 ]; then
          echo "Failed to fetch code scanning results"
          exit 1
        fi
        echo "$results" > results.json

        if [ "$SORT_BY_NEWEST" == "true" ]; then
          vulnerabilities=$(jq '[.[] | select(.state == "open")] | sort_by(.created_at) | reverse' results.json)
        else
          vulnerabilities=$(jq '[.[] | select(.state == "open")] | sort_by(.created_at) | reverse | sort_by(.rule.security_severity_level)' results.json)
        fi

        echo "$vulnerabilities" > vulnerabilities.json
        total_vulnerabilities=$(jq length vulnerabilities.json)
        echo "total_vulnerabilities=$total_vulnerabilities" >> $GITHUB_ENV

    - name: Construct Slack message
      id: construct-slack-message
      shell: bash
      env:
        MAX_ALERTS: ${{ inputs.max-alerts }}
        TOTAL_VULNERABILITIES: ${{ env.total_vulnerabilities }}
      run: |
        vulnerabilities=$(cat vulnerabilities.json)

        if [ "$vulnerabilities" != '[]' ]; then
          echo "Vulnerabilities have been found during code scanning."
          echo "Code Scanning Vulnerabilities:"
          echo "$vulnerabilities"
          message="*:warning: Vulnerabilities discovered during code scanning.* \n*Code Scanning Vulnerabilities:*"

          vulnerabilities=$(echo "$vulnerabilities" | jq -c '.[:$MAX_ALERTS] | .[] | {code: (.rule.tags[] | select(startswith("external/cwe/"))), date: .created_at, severity: .rule.security_severity_level, url: .html_url}')
          for vulnerability in $vulnerabilities; do
            code=$(echo $vulnerability | jq -r '.code')
            date=$(echo $vulnerability | jq -r '.date' | sed 's/T/ /' | sed 's/Z//')
            severity=$(echo $vulnerability | jq -r '.severity')
            url=$(echo $vulnerability | jq -r '.url')
            message="$message \n\n*Code:* $code \n*Date:* $date \n*Severity:* $severity \n*URL:* $url"
          done

          if [ "$TOTAL_VULNERABILITIES" -gt "$MAX_ALERTS" ]; then
            remaining_count=$((TOTAL_VULNERABILITIES - MAX_ALERTS))
            message="$message \n\nand *$remaining_count* more vulnerabilities"
          fi

        else
          message="*:white_check_mark: No new vulnerabilities have been found.*"
        fi
        echo "message=$message" >> $GITHUB_OUTPUT

    - name: Send Slack Message
      uses: 3lvia/core-github-actions-templates/slack-message@trunk
      with:
        message: ${{ steps.construct-slack-message.outputs.message }}
        slack-api-token: ${{ inputs.slack-api-token }}
        slack-channel: ${{ inputs.slack-channel }}
