name: 'Deploy Argo CD'
description: |
  Deploys an application to Kubernetes using Argo CD.
inputs:
  name:
    description: 'Name of application. Do not include namespace.'
    required: true
  system:
    description: 'System (namespace) of the application.'
    required: true
  image-repository:
    description: "Repository of the Docker image to deploy, e.g. 'containerregistryelvia.azurecr.io'."
    required: false
    default: ''
  image-digest:
    description: 'Digest of the Docker image to deploy, e.g. sha256:1234567890abcdef...'
    required: true
  environment:
    description: 'Environment to deploy to.'
    required: true
  checkout:
    description: 'If `true`, the action will check out the repository. If `false`, the action will assume the repository has already been checked out.'
    required: false
    default: 'true'
  slack-channel:
    description: 'Slack channel to notify on failure. Leave empty to disable notifications.'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Validate required inputs
      shell: bash
      run: |
        if [[ -z "$NAME" ]]; then
          echo "Error: input 'name' is required."
          exit 1
        fi

        if [[ -z "$SYSTEM" ]]; then
          echo "Error: input 'system' is required."
          exit 1
        fi

        if [[ -z "$IMAGE_DIGEST" ]]; then
          echo "Error: input 'image-digest' is required."
          exit 1
        fi

        if [[ -z "$ENVIRONMENT" ]]; then
          echo "Error: input 'environment' is required."
          exit 1
        fi
      env:
        NAME: ${{ inputs.name }}
        SYSTEM: ${{ inputs.system }}
        IMAGE_DIGEST: ${{ inputs.image-digest }}
        ENVIRONMENT: ${{ inputs.environment }}

    - name: Install OIDC Client from Core Package
      shell: bash
      run: npm install @actions/core@1.11.1 @actions/http-client

    - name: Get OIDC Token
      uses: actions/github-script@v7
      id: get-token
      with:
        script: |
          const core_ = require('@actions/core')
          let idToken = await core_.getIDToken()
          core_.setOutput('token', idToken)

    # TODO: use prod deployment of deployvia
    - name: Send deployment request
      shell: bash
      run: |
        curl -v \
          -X POST \
          -H "X-GitHub-OIDC-Token: $GH_ID_TOKEN" \
          -H "Content-Type: application/json" \
          -d "{\"image_repository\": \"$IMAGE_REPOSITORY\",\"image_digest\":\"$IMAGE_DIGEST\",\"system\": \"$SYSTEM\",\"environment\": \"$ENVIRONMENT\",\"application_name\": \"$NAME\"}" \
          --fail-with-body \
          https://coregke.dev-elvia.io/deployvia/deployment
      env:
        GH_ID_TOKEN: ${{ steps.get-token.outputs.token }}
        IMAGE_REPOSITORY: ${{ inputs.image-repository }}
        IMAGE_DIGEST: ${{ inputs.image-digest }}
        SYSTEM: ${{ inputs.system }}
        ENVIRONMENT: ${{ inputs.environment }}
        NAME: ${{ inputs.name }}
