name: 'Deploy Argo CD'
description: 'Deploys an application to Kubernetes using Argo CD.'
inputs:
  name:
    description: 'Name of application. Do not include namespace.'
    required: true
  system:
    description: 'System (namespace) of the application.'
    required: true
  image:
    description: 'Name of image to deploy with digest (but without tag!), e.g. `containerregistryelvia.azurecr.io/core/demo-api-go@sha256:123456789abdefgh`.'
    required: true
  cluster-type:
    description: 'Type of cluster to check deployment status for. Can be `aks`, `gke` or `iss`.'
    required: true
    default: 'aks'
  check-all-clusters:
    description: |
      If `true`, the action will check all clusters for deployment status.
      If `false`, the action will only check the cluster specified in `cluster-type`.
    required: false
    default: 'false'
  environment:
    description: 'Environment to deploy to.'
    required: true
  registry:
    description: 'Docker registry to use.'
    required: false
    default: 'containerregistryelvia.azurecr.io'
  ACR_USERNAME:
    description: 'Username for Azure Container Registry, if using it.'
    required: true
  ACR_PASSWORD:
    description: 'Password for Azure Container Registry, if using it.'
    required: true
  checkout:
    description: |
      If `true`, the action will check out the repository. If `false`, the action will assume the repository has already been checked out.
    required: false
    default: 'true'
  slack-channel:
    description: 'Slack channel to notify on failure. Leave empty to disable notifications.'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Validate required inputs
      shell: bash
      run: |
        if [[ -z "$NAME" ]]; then
          echo "Error: input 'name' is required."
          exit 1
        fi

        if [[ -z "$SYSTEM" ]]; then
          echo "Error: input 'system' is required."
          exit 1
        fi

        if [[ -z "$ENVIRONMENT" ]]; then
          echo "Error: input 'environment' is required."
          exit 1
        fi

        if [[ -z "$ACR_USERNAME" ]]; then
          echo "Error: input 'ACR_USERNAME' is required."
          exit 1
        fi

        if [[ -z "$ACR_PASSWORD" ]]; then
          echo "Error: input 'ACR_PASSWORD' is required."
          exit 1
        fi
      env:
        NAME: ${{ inputs.name }}
        SYSTEM: ${{ inputs.system }}
        ENVIRONMENT: ${{ inputs.environment }}
        ACR_USERNAME: ${{ inputs.ACR_USERNAME }}
        ACR_PASSWORD: ${{ inputs.ACR_PASSWORD }}

    #   - name: Login to GitHub Container Registry
    #     if: contains(inputs.registry, 'ghcr.io')
    #     uses: docker/login-action@v3
    #     with:
    #       registry: 'ghcr.io'
    #       username: ${{ github.actor }}
    #       password: ${{ secrets.GITHUB_TOKEN }}

    - name: Login to Azure Container Registry
      if: contains(inputs.registry, 'azurecr.io')
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.ACR_USERNAME }}
        password: ${{ inputs.ACR_PASSWORD }}

    - name: Copy image to tag '${{ inputs.environment }}'
      shell: bash
      run: |
        image_without_tag_and_or_digest="$(echo $IMAGE | cut -d':' -f1 | cut -d'@' -f1)"

        docker run --rm \
          --env SRC_CREDS="$ACR_USERNAME:$ACR_PASSWORD" \
          --env DEST_CREDS="$ACR_USERNAME:$ACR_PASSWORD" \
          --env IMAGE="$IMAGE" \
          --env IMAGE_WITHOUT_TAG_AND_OR_DIGEST="$image_without_tag_and_or_digest" \
          --env ENVIRONMENT="$ENVIRONMENT" \
          quay.io/skopeo/stable:latest \
          sh -c 'skopeo copy --preserve-digests --src-creds="$SRC_CREDS" --dest-creds="$DEST_CREDS" docker://$IMAGE docker://$IMAGE_WITHOUT_TAG_AND_OR_DIGEST:$ENVIRONMENT'
      env:
        ACR_USERNAME: ${{ inputs.ACR_USERNAME }}
        ACR_PASSWORD: ${{ inputs.ACR_PASSWORD }}
        ENVIRONMENT: ${{ inputs.environment }}
        IMAGE: ${{ inputs.image }}

    - name: Get OIDC token
      shell: bash
      id: get-token
      run: |
        # Get OIDC token from GitHub Actions
        token=$(curl -s -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r '.value')
        echo "::add-mask::$token"
        echo "token=$token" >> "$GITHUB_OUTPUT"

    - name: Wait for Argo CD application to sync
      shell: bash
      run: |
        # Wait for Argo CD application to sync
        curl -v \
          -H "X-GitHub-OIDC-Token: $GH_ID_TOKEN" \
          -H 'X-Timeout: 5m' \
          -H 'Content-Type: application/json' \
          -d "{\"image\":\"$IMAGE\",\"system\":\"$SYSTEM\",\"cluster_type\":\"$CLUSTER_TYPE\",\"environment\":\"$ENVIRONMENT\",\"application_name\":\"$NAME\",\"check_all_clusters\":$CHECK_ALL_CLUSTERS}" \
          --fail-with-body \
          "$DEPLOYVIA_URL"
      env:
        GH_ID_TOKEN: ${{ steps.get-token.outputs.token }}
        NAME: ${{ inputs.name }}
        SYSTEM: ${{ inputs.system }}
        CLUSTER_TYPE: ${{ inputs.cluster-type }}
        CHECK_ALL_CLUSTERS: ${{ inputs.check-all-clusters }}
        ENVIRONMENT: ${{ inputs.environment }}
        IMAGE: ${{ inputs.image }}
        DEPLOYVIA_URL: ${{ format('https://deployvia.{0}/deployment', (inputs.environment == 'sandbox' && 'dev-elvia.io' || 'elvia.io')) }}

    - name: Notify Slack on failure
      if: ${{ failure() && inputs.slack-channel != '' }}
      uses: 3lvia/core-github-actions-templates/slack-message@trunk
      with:
        system: ${{ inputs.system }}
        environment: ${{ inputs.environment }}
        slack-channel: ${{ inputs.slack-channel }}
        message: |
          :warning: *Deploy feilet* :warning:
          GitHub Actions feilet under deploy av *${{ inputs.system }}/${{ inputs.name }}* i miljøet *${{ inputs.environment }}*.
          Se <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|her> for detaljer.
