name: 'Deploy Argo CD'
description: 'Deploys an application to Kubernetes using Argo CD.'
inputs:
  name:
    description: 'Name of application. Do not include namespace.'
    required: true
  system:
    description: 'System (namespace) of the application.'
    required: true
  environment:
    description: 'Environment to deploy to.'
    required: true
  image:
    description: 'Image to deploy.'
    required: true
  registry:
    description: 'Docker registry to use.'
    required: false
    default: 'containerregistryelvia.azurecr.io'
  AZURE_TENANT_ID:
    description: 'Azure Tenant ID for authentication.'
    required: false
    default: '2186a6ec-c227-4291-9806-d95340bf439d'
  AZURE_CLIENT_ID:
    description: 'Azure Client ID for authentication.'
    required: true
  AZURE_SUBSCRIPTION_ID:
    description: 'Azure Subscription ID for authentication.'
    required: false
    default: '9edbf217-b7c1-4f6a-ae76-d046cf932ff0'
  checkout:
    description: 'If `true`, the action will check out the repository. If `false`, the action will assume the repository has already been checked out.'
    required: false
    default: 'true'
  slack-channel:
    description: 'Slack channel to notify on failure. Leave empty to disable notifications.'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Validate required inputs
      shell: bash
      run: |
        if [[ -z "$NAME" ]]; then
          echo "Error: input 'name' is required."
          exit 1
        fi

        if [[ -z "$SYSTEM" ]]; then
          echo "Error: input 'system' is required."
          exit 1
        fi

        if [[ -z "$ENVIRONMENT" ]]; then
          echo "Error: input 'environment' is required."
          exit 1
        fi

        if [[ -z "$AZURE_CLIENT_ID" ]]; then
          echo "Error: input 'AZURE_CLIENT_ID' is required."
          exit 1
        fi
      env:
        NAME: ${{ inputs.name }}
        SYSTEM: ${{ inputs.system }}
        ENVIRONMENT: ${{ inputs.environment }}
        AZURE_CLIENT_ID: ${{ inputs.AZURE_CLIENT_ID }}

    - name: Azure login
      uses: azure/login@v2
      with:
        tenant-id: ${{ inputs.AZURE_TENANT_ID }}
        client-id: ${{ inputs.AZURE_CLIENT_ID }}
        subscription-id: ${{ inputs.AZURE_SUBSCRIPTION_ID }}

    - name: Install skopeo
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y skopeo

    - name: Copy image to new tag
      shell: bash
      run: skopeo copy "docker://$IMAGE_NAME:$IMAGE_TAG" "docker://$IMAGE_NAME:$ENVIRONMENT"
      env:
        ENVIRONMENT: ${{ inputs.environment }}
        IMAGE_NAME: ${{ contains(inputs.registry, 'azurecr.io') && format('{0}/{1}-{2}', inputs.registry, inputs.name, inputs.system) || format('{0}/{1}/{2}', inputs.registry, inputs.name, inputs.system) }}
        IMAGE_TAG: ${{ format('{0}-{1}', github.sha, github.run_number) }}
