name: 'ISS Tag & Push Image'
description: |
  Pulls image from GHCR, re-tags it and pushes it to GCR.

  *Only useful for ISS deployments.*
inputs:
  old-image-name-with-tag:
    description: 'Name of the Docker image to pull from GHCR, including the tag.'
    required: true
  new-image-name:
    description: 'Name of the Docker image to push to GCR, without the tag.'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Login to GHCR
      uses: docker/login-action@06fb636fac595d6fb4b28a5dfcb21a6f5091859c # v4.5.0
      with:
        registry: 'ghcr.io'
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Pull image from GHCR, re-tag and push to GCR
      shell: bash
      run: |
        tag=$(echo "$OLD_IMAGE_NAME_WITH_TAG" | cut -d ':' -f 2)
        new_image_name_with_tag="$NEW_IMAGE_NAME:$tag"

        docker pull "$OLD_IMAGE_NAME_WITH_TAG"
        docker tag "$OLD_IMAGE_NAME_WITH_TAG" "$new_image_name_with_tag"
        docker push "$new_image_name_with_tag"
      env:
        OLD_IMAGE_NAME_WITH_TAG: ${{ inputs.old-image-name-with-tag }}
        NEW_IMAGE_NAME: ${{ inputs.new-image-name }}
