name: 'Analyze'
description: 'Run CodeQL analysis.'
inputs:
  working-directory:
    description: 'Will run CodeQL Analysis on projects under this working directory'
    required: false
    default: './'
  checkout:
    description: 'If "true", the action will check out the repository. If "false", the action will assume the repository has already been checked out.'
    required: false
    default: 'true'
  languages:
    description: 'Languages to run CodeQL analyze on.'
    required: false
    default: 'javascript-typescript, csharp, python, go'

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      if: ${{ inputs.checkout == 'true' }}
      uses: actions/checkout@v4

    - name: Create codeql-config
      shell: bash
      run: |
        cat <<EOF > codeql-config.yml
        name: "CodeQL config"
        paths:
          - ${{ inputs.working-directory }}
        EOF
        echo "codeql-config.yml:"
        cat codeql-config.yml

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        config-file: codeql-config.yml
        languages: ${{ inputs.languages }}

    - name: Build projects
      shell: bash
      run: |
        projects=`find . -iname "*csproj"`
        for project in $projects;
        do
          dotnet build $project
        done
      working-directory: ${{ inputs.working-directory }}

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        config-file: codeql-config.yml
