name: 'Analyze'
description: 'Run CodeQL analysis.'
inputs:
  working-directory:
    description: 'Will run CodeQL Analysis on projects under this working directory'
    required: false
    default: './'

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3

    - name: Build projects
      shell: bash
      run: |
        projects=`find . -iname "*csproj"`
        for project in $projects;
        do
          dotnet build $project
        done
      working-directory: ${{ inputs.working-directory }}

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
