name: 'Analyze'
description: 'Run CodeQL analysis.'
inputs:
  checkout:
    description: 'If `true`, the action will check out the repository. If `false`, the action will assume the repository has already been checked out.'
    required: false
    default: 'true'
  working-directory:
    description: Will run CodeQL Analysis on projects under this working directory.
    required: false
    default: './'
  dotnet-tool-manifest:
    description: |
      Path to the .NET tool manifest file, relative to the root of the repository.
      Only needed if you require .NET tools that are outside of `working-directory` for the build.
    required: false
    default: './.config/dotnet-tools.json'
  language:
    description: 'Language to run CodeQL analyze on. Use a matrix strategy to run for multiple languages.'
    required: false
    default: 'csharp'
  upload-results:
    description: 'If `true` the action will upload CodeQL results to GitHub Security Code Scanning. If `false`, the action will not upload results.'
    required: false
    default: 'true'
  codeql-results-ref:
    description: |
      The ref where CodeQL results will be uploaded. Defaults to `github.ref`.
      ONLY USED FOR INTERNAL TESTING.
    required: false
  codeql-results-sha:
    description: |
      The sha of the HEAD of the ref where CodeQL results will be uploaded. Defaults to `github.sha`.
      ONLY USED FOR INTERNAL TESTING.
    required: false

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      if: ${{ inputs.checkout == 'true' }}
      uses: actions/checkout@v4

    - name: Create codeql-config
      shell: bash
      run: |
        cat <<EOF > codeql-config.yml
        name: "CodeQL config"
        paths:
          - ${{ inputs.working-directory }}
        EOF
        echo "codeql-config.yml:"
        cat codeql-config.yml

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        config-file: 'codeql-config.yml'
        languages: ${{ inputs.language }}

    - name: Restore .NET tools
      if: ${{ inputs.language == 'csharp' }}
      shell: bash
      run: dotnet tool restore --tool-manifest '${{ inputs.dotnet-tool-manifest }}'

    - name: Build projects
      if: ${{ inputs.language == 'csharp' }}
      shell: bash
      run: |
        projects=$(find . -iname "*csproj")
        for project in $projects;
        do
          dotnet build "$project"
        done
      working-directory: ${{ inputs.working-directory }}

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        ref: ${{ inputs.codeql-results-ref == '' && github.ref || inputs.codeql-results-ref }}
        sha: ${{ inputs.codeql-results-sha == '' && github.sha || inputs.codeql-results-sha }}
        upload-database: ${{ inputs.upload-results }}
