name: 'Analyze'
description: 'Run CodeQL analysis.'
inputs:
  working-directory:
    description: 'Will run CodeQL Analysis on projects under this working directory'
    required: false
    default: './'
  checkout:
    description: 'If "true", the action will check out the repository. If "false", the action will assume the repository has already been checked out.'
    required: false
    default: 'true'
  dotnet-version:
    description: 'Version of .NET to use.'
    required: false
    default: '8.x'

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      if: ${{ inputs.checkout == 'true' }}
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Build projects
      shell: bash
      run: |
        projects=`find . -iname "*csproj"`
        for project in $projects;
        do
          dotnet build $project
        done
      working-directory: ${{ inputs.working-directory }}

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
