name: Unit Test
description: 'Run dotnet unit tests.'
inputs:
  checkout:
    description: 'If "true", the action will check out the repository. If "false", the action will assume the repository has already been checked out.'
    required: false
    default: 'true'
  working-directory:
    description: 'Will run unit tests on projects under this working directory'
    required: false
    default: './'
  test-projects:
    description: 'Pattern to use to find test projects. Defaults to *unit*test*csproj'
    required: false
    default: '*unit*test*csproj'
  dotnet-version:
    description: 'Version of .NET to use.'
    required: false
    default: '8.x'

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      if: ${{ inputs.checkout == 'true' }}
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Run unit tests
      shell: bash
      run: |
        testprojects=`find . -iname "${{ inputs.test-projects }}"`
        for testproject in $testprojects;
        do
          dotnet test -l:trx $testproject
        done
      working-directory: ${{ inputs.working-directory }}

    - name: Publish test results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
          **/TestResults/*.trx
          .github/**/TestResults/*.trx
        check_name: Unit Test Results
