name: Integration Test
description: 'Run .NET integration tests.'
inputs:
  checkout:
    description: 'If `true`, the action will check out the repository. If `false`, the action will assume the repository has already been checked out.'
    required: false
    default: 'true'
  system:
    description: 'System is used to log in to Vault using correct role.'
    required: true
  working-directory:
    description: 'Will run integration tests on projects under this working directory.'
    required: false
    default: './'
  dotnet-tool-manifest:
    description: |
      Path to the .NET tool manifest file, relative to the root of the repository.
      Only needed if you require .NET tools that are outside of `working-directory` for the build.
    required: false
    default: './.config/dotnet-tools.json'
  test-projects:
    description: 'Pattern to use to find test projects.'
    required: false
    default: 'integration*test*csproj'
  environment:
    description: 'Environment is used to find correct Vault instance.'
    required: true
    default: 'dev'
  slack-channel:
    description: 'Slack channel to notify on failure. Leave empty to disable notifications'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      if: ${{ inputs.checkout == 'true' }}
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Login Vault and export token
      uses: 3lvia/core-github-actions-templates/vault@trunk
      with:
        system: ${{ inputs.system }}
        environment: ${{ inputs.environment }}
        exportToken: 'true'

    - name: Restore .NET tools
      shell: bash
      run: dotnet tool restore --tool-manifest "$DOTNET_TOOL_MANIFEST"
      env:
        DOTNET_TOOL_MANIFEST: ${{ inputs.dotnet-tool-manifest }}

    - name: Run integration tests
      shell: bash
      run: |
        testprojects=$(find . -ipath "*$TEST_PROJECTS")
        if [[ -z $testprojects ]]; then
            echo "Unable to find any dotnet projects matching the pattern $TEST_PROJECTS. Set the pattern using the parameter test-projects."
            exit 0 # TODO: Fail the action if no test projects are found
        else
            echo "Running dotnet test on test projects: $testprojects"
        fi

        for testproject in $testprojects; do
          dotnet test -l:trx "$testproject"
        done
      env:
        TEST_PROJECTS: ${{ inputs.test-projects }}
      working-directory: ${{ inputs.working-directory }}

    - name: Publish test results
      uses: EnricoMi/publish-unit-test-result-action@d0a4676d0e0b938bc201470d88276b7c74c712b3 # v2.24.0
      if: always()
      with:
        files: |
          **/TestResults/*.trx
          .github/**/TestResults/*.trx
        check_name: 'Integration Test Results'

    - name: Notify Slack on failure
      if: ${{ failure() && inputs.slack-channel != '' }}
      uses: 3lvia/core-github-actions-templates/slack-message@trunk
      with:
        system: ${{ inputs.namespace }}
        environment: ${{ inputs.environment }}
        slack-channel: ${{ inputs.slack-channel }}
        message: |
          :warning: ${{ github.repository }} - ${{ github.ref_name }} feilet. Se https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} for detaljer.
