name: Playwright Test
description: 'Run Playwright tests written in .NET.'
inputs:
  test-project:
    description: 'Name of test project file to run.'
    required: true
  environment:
    description: 'Environment is used to find correct Vault instance.'
    required: true
  system:
    description: 'System is used to log in to Vault using correct role.'
    required: true
  checkout:
    description: 'If `true`, the action will check out the repository. If `false`, the action will assume the repository has already been checked out.'
    required: false
    default: 'true'
  configuration:
    description: 'Value to set for the `--configuration` flag when running `dotnet test`.'
    required: false
    default: 'Debug'

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      if: ${{ inputs.checkout == 'true' }}
      uses: actions/checkout@v5

    - name: Login Vault and export token
      uses: 3lvia/core-github-actions-templates/vault@trunk
      with:
        system: ${{ inputs.system }}
        environment: ${{ inputs.environment }}
        exportToken: 'true'

    - name: Build .NET project
      shell: bash
      run: dotnet build '${{ inputs.test-project }}'

    - name: Install playwright
      shell: pwsh
      run: |
        $dirName = [System.IO.Path]::GetDirectoryName("${{ inputs.test-project }}")
        $playwrightscript = Get-ChildItem -Path $dirName -Filter playwright.ps1 -Recurse -ErrorAction SilentlyContinue -Force
        &$playwrightscript.FullName install

    - name: Run .NET tests
      shell: bash
      run: dotnet test -l:trx --configuration '${{ inputs.configuration }}' '${{ inputs.test-project }}'

    - name: Publish test results
      uses: EnricoMi/publish-unit-test-result-action@3a74b2957438d0b6e2e61d67b05318aa25c9e6c6 # v2.20.0
      if: always()
      with:
        files: |
          **/TestResults/*.trx
          .github/**/TestResults/*.trx
        check_name: 'Smoketest Results'
