name: Build and deploy to Kubernetes on Google Cloud

on:
  push:
    branches: [trunk]
  pull_request:
    branches: [trunk]
  # NOTE: this is for internal testing, remove this line when copying to your project
  workflow_call:
  # NOTE: this is for internal testing, remove this line when copying to your project

env:
  APPLICATION_NAME: 'demo-api'
  SYSTEM_NAMESPACE: 'core'

jobs:
  unittests:
    name: Run unit tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      issues: read
      pull-requests: write
    steps:
      - uses: 3lvia/core-github-actions-templates/unittest@trunk

  analyze:
    name: Run CodeQL analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: 3lvia/core-github-actions-templates/unittest@trunk

  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    environment: build
    steps:
      - uses: 3lvia/core-github-actions-templates/build@trunk
        with:
          name: ${{ env.APPLICATION_NAME }}
          namespace: ${{ env.SYSTEM_NAMESPACE }}
          dockerfile: '.github/test/src/Dockerfile'
          AZURE_CLIENT_ID: ${{ vars.ACR_CLIENT_ID }}

  deploy-dev:
    name: Deploy to dev
    needs: [build, analyze]
    runs-on: ubuntu-latest
    permissions:
     contents: read
     id-token: write
    environment: dev
    steps:
      - uses: 3lvia/core-github-actions-templates/deploy@trunk
        with:
          name: ${{ env.APPLICATION_NAME }}
          namespace: ${{ env.SYSTEM_NAMESPACE }}
          environment: 'dev'
          helm-values-path: '.github/test/deploy/values.yaml'
          runtime-cloud-provider: 'GKE'
          GC_SERVICE_ACCOUNT: ${{ vars.GC_SERVICE_ACCOUNT }}
          GC_WORKLOAD_IDENTITY_PROVIDER: ${{ vars.GC_WORKLOAD_IDENTITY_PROVIDER }}

  deploy-test:
    name: Deploy to test
    needs: [deploy-dev]
    runs-on: ubuntu-latest
    permissions:
     contents: read
     id-token: write
    environment: test
    # Only on push to trunk
    if: github.ref == 'refs/heads/trunk'
    steps:
      - uses: 3lvia/core-github-actions-templates/deploy@trunk
        with:
          name: ${{ env.APPLICATION_NAME }}
          namespace: ${{ env.SYSTEM_NAMESPACE }}
          environment: 'prod'
          helm-values-path: '.github/test/deploy/values.yaml'
          runtime-cloud-provider: 'GKE'
          GC_SERVICE_ACCOUNT: ${{ vars.GC_SERVICE_ACCOUNT }}
          GC_WORKLOAD_IDENTITY_PROVIDER: ${{ vars.GC_WORKLOAD_IDENTITY_PROVIDER }}

  deploy-prod:
    name: Deploy to prod
    needs: [deploy-test]
    runs-on: ubuntu-latest
    permissions:
     contents: read
     id-token: write
    environment: test
    # Only on push to trunk
    if: github.ref == 'refs/heads/trunk'
    steps:
      - uses: 3lvia/core-github-actions-templates/deploy@trunk
        with:
          name: ${{ env.APPLICATION_NAME }}
          namespace: ${{ env.SYSTEM_NAMESPACE }}
          environment: 'prod'
          helm-values-path: '.github/test/deploy/values.yaml'
          runtime-cloud-provider: 'GKE'
          GC_SERVICE_ACCOUNT: ${{ vars.GC_SERVICE_ACCOUNT }}
          GC_WORKLOAD_IDENTITY_PROVIDER: ${{ vars.GC_WORKLOAD_IDENTITY_PROVIDER }}
