name: Trivy IaC scan
description: 'Uses https://github.com/aquasecurity/trivy-action to scan IaC and report security issues. The action will report any vulnerabilities to GitHub Advanced Security, which will be visible in the Security tab on GitHub. If this action is ran on a pull request, GitHub Advanced Security will give a detailed report of any vulnerabilities introduced by new changes in the pull request.'
inputs:
  path:
    description: 'Path to the directory containing the IaC files.'
    required: false
    default: '.'
  skip-dirs:
    description: 'Comma-separated list of directories to skip.'
    required: false
  severity:
    description: 'Severity levels to scan for. See https://github.com/aquasecurity/trivy-action?tab=readme-ov-file#inputs for more information.'
    required: false
    default: 'CRITICAL,HIGH,MEDIUM,LOW,UNKNOWN'
  upload-report:
    description: 'Upload Trivy report to GitHub Security tab. GitHub Advanced Security must be enabled for the repository to use this feature.'
    required: false
    default: 'true'
  checkout:
    description: 'If true, the action will check out the repository. If false, the action will assume the repository has already been checked out.'
    required: false
    default: 'true'
  trivyignore:
    description: "Path to the Trivy ignore file in the repository. This action will add a default set of CVE's that are ignored for all scans. If you wish to add more CVE's to ignore, add them to the .trivyignore, or create a new file and specify the path here. See https://aquasecurity.github.io/trivy/v0.50/docs/configuration/filtering/#by-finding-ids for more information."
    required: false
    default: '.trivyignore'

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      if: ${{ inputs.checkout == 'true' }}
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set env
      shell: bash
      run: |
        echo "TRIVY_SARIF=trivy.sarif" >> $GITHUB_ENV

    - name: Set .trivyignore
      shell: bash
      run: |
        # Add default set of CVE's to ignore
        echo "AVD-DS-0026" >> '${{ inputs.trivyignore }}'

    - name: Run Trivy vulnerability scanner in IaC mode
      uses: aquasecurity/trivy-action@0.20.0
      with:
        scan-type: 'config'
        format: 'sarif'
        exit-code: '0'
        output: ${{ env.TRIVY_SARIF }}
        severity: ${{ inputs.severity }}
        trivyignores: ${{ inputs.trivyignore }}
        ignore-unfixed: 'true'
        skip-dirs: ${{ inputs.skip-dirs }}

    - name: Upload Trivy report to GitHub Security tab
      if: ${{ inputs.upload-report == 'true' }}
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ env.TRIVY_SARIF }}
        category: 'Trivy'
