parameters:
  - name: environment
  - name: agent_pool
  - name: target_host
  - name: target_path
  - name: service_name
  - name: serviceuser_user
  - name: serviceuser_password
  - name: replace_target_files
  - name: vault_addr
  - name: role_id
  - name: variables
    type: object
  - name: run_install_script
    type: boolean
    default: true
  - name: drop
    default: drop
  
jobs:
- deployment: DeployToService
  displayName: Deploy to Service ${{ parameters.environment }}
  environment: ${{ parameters.environment }}
  pool:
    name: ${{ parameters.agent_pool }}
  strategy:
    runOnce:
      deploy:
        steps:
          - download: none
          - checkout: 'templates'
            path: templates
          - task: UsePythonVersion@0
            displayName: "Use Python 3.9"
            inputs:
              versionSpec: 3.9
          # Rewrite instruction: Use vault action to get secrets from vault and set them as environment variables
          - task: PythonScript@0
            displayName: Run python script to set variables
            inputs:
              scriptPath: $(Pipeline.Workspace)/templates/set-variables-from-vault/set-variables-from-vault.py
              arguments: --json_params "${{ convertToJson(parameters.variables) }}"
            env:
              ROLE_ID: ${{ parameters.role_id }}
              VAULT_ADDR: ${{ parameters.vault_addr }}
          - task: PowerShellOnTargetMachines@3
            displayName: "Run PowerShell: Test connection to server"
            inputs:
              machines: ${{ parameters.target_host }}
              userName: $(agentuser)
              userPassword: $(agentpass)
              scriptType: 'Inline'
              inlineScript: 'Write-Output "Intility connection working"'
              communicationProtocol: 'http'
          - task: DownloadPipelineArtifact@2
            displayName: "Download application zipfile"
            inputs:
              artifact: ${{ parameters.drop }}
              path: '$(Pipeline.Workspace)\${{ parameters.drop }}'
              patterns: '**/*.zip'
          - task: ExtractFiles@1
            displayName: "Extract application zipfile"
            inputs:
              destinationFolder: $(Pipeline.Workspace)\${{ parameters.service_name }}\installation
              archiveFilePatterns: '$(Pipeline.Workspace)\${{ parameters.drop }}\*.zip'
              cleanDestinationFolder: true
          - task: qetza.replacetokens.replacetokens-task.replacetokens@3
            displayName: "Replace tokens in config-files"
            inputs:
              rootDirectory: $(Pipeline.Workspace)\${{ parameters.service_name }}\installation
              targetFiles: ${{ parameters.replace_target_files }}
          - task: WindowsMachineFileCopy@2
            displayName: "Copy application files to remote server"
            inputs:
              machineNames: ${{ parameters.target_host }}
              adminUserName: $(agentuser)
              adminPassword: $(agentpass)
              targetPath: ${{ parameters.target_path }}\${{ parameters.service_name }}-${{ parameters.environment }}\installation
              sourcePath: $(Pipeline.Workspace)\${{ parameters.service_name }}\installation
              cleanTargetBeforeCopy: true
          - task: WindowsMachineFileCopy@2
            displayName: "Copy Powershell installation files to remote server"
            inputs:
              machineNames: ${{ parameters.target_host }}
              adminUserName: $(agentuser)
              adminPassword: $(agentpass)
              targetPath: '${{ parameters.target_path }}\${{ parameters.service_name }}-${{ parameters.environment }}\scripts'
              sourcePath: '$(Pipeline.Workspace)/templates/intility/scripts'
              cleanTargetBeforeCopy: true
          - task: PowerShellOnTargetMachines@3
            displayName: "Run PowerShell: Installscript"
            condition: eq( ${{ parameters.run_install_script }}, true )
            inputs:
              machines: ${{ parameters.target_host }}
              adminUserName: $(agentuser)
              adminPassword: $(agentpass)
              ScriptType: FilePath
              ScriptPath: '${{ parameters.target_path }}\${{ parameters.service_name }}-${{ parameters.environment }}\scripts\InstallService.ps1'
              ScriptArguments: '${{parameters.service_name}}-${{ parameters.environment }} ${{parameters.service_name}}-${{ parameters.environment }} ${{parameters.service_name}}-${{ parameters.environment }} ${{ parameters.target_path }}\${{ parameters.service_name }}-${{ parameters.environment }}\application ${{parameters.service_name}}.exe "${{parameters.serviceuser_user}}" "${{parameters.serviceuser_password}}" ${{ parameters.target_path }}\${{ parameters.service_name }}-${{ parameters.environment }}\installation'
              communicationProtocol: 'http'