name: Vault
description: "Get secrets from Elvia's Vault."
inputs:
  system:
    description: 'System name is used to log in to Vault using the correct role.'
    required: true
  environment:
    description: 'Environment is used to find correct Vault instance.'
    required: true
    default: 'dev'
  secrets:
    description: 'Secrets to fetch from Vault; see [here](https://github.com/hashicorp/vault-action?tab=readme-ov-file#multiple-secrets) for syntax.'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set Vault address based on environment
      shell: bash
      run: |
        # Set Vault address based on environment
        if [[ '${{ inputs.environment }}' == 'dev' || '${{ inputs.environment }}' == 'test' ]]; then
          echo 'VAULT_ADDR=https://vault.${{ inputs.environment }}-elvia.io' >> "$GITHUB_ENV"
        elif [[ '${{ inputs.environment }}' == 'prod' ]]; then
          echo 'VAULT_ADDR=https://vault.elvia.io' >> "$GITHUB_ENV"
        else
          echo 'Unsupported environment: ${{ inputs.environment }}'
          exit 1
        fi

        echo "REPO_SHORT_NAME=${GITHUB_REPOSITORY##*/}" >> "$GITHUB_ENV"

    - name: Login to Vault and export token
      uses: hashicorp/vault-action@v3
      with:
        url: ${{ env.VAULT_ADDR }}
        role: 'jwt-github-${{ inputs.system }}-${{ env.REPO_SHORT_NAME }}'
        method: 'jwt'
        path: 'jwt-github'
        secrets: |
          ${{ inputs.secrets }}

    - name: Show message on failure
      if: failure()
      shell: bash
      run: |
        echo "To access Vault, this repository must be added to https://github.com/3lvia/github-repositories-terraform/tree/trunk/systems"
        exit 1
