name: Vault
description: "Get secrets from Elvia's Vault for use in GitHub Actions."
inputs:
  system:
    description: 'System name is used to log in to Vault using the correct role.'
    required: true
  environment:
    description: 'Environment is used to find correct Vault instance.'
    default: 'dev'
  secrets:
    description: 'Secrets to fetch from Vault; see [here](https://github.com/hashicorp/vault-action?tab=readme-ov-file#multiple-secrets) for syntax.'
  exportToken:
    description: |
      Whether to export the Vault token as an environment variable. Set this to true if you need to be authenticated to Vault in subsequent steps.
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Check inputs
      shell: bash
      run: |
        # Explicit checks for required inputs, due to https://github.com/actions/runner/issues/1070
        [[ "$SYSTEM" ]] || { echo "Parameter 'system' is required, but is empty." ; exit 1; }
      env:
        SYSTEM: ${{ inputs.system }}

    - name: Set Vault address based on environment
      shell: bash
      run: |
        # Set Vault address based on environment
        if [[ "$ENVIRONMENT" == 'dev' || "$ENVIRONMENT" == 'sandbox' ]]; then
          echo 'VAULT_ADDR=https://vault.dev-elvia.io' >> "$GITHUB_ENV"
        elif [[ "$ENVIRONMENT" == 'kptest' ]]; then
          echo 'VAULT_ADDR=https://vault.kptest-elvia.io' >> "$GITHUB_ENV"
        elif [[ "$ENVIRONMENT" == 'test' ]]; then
          echo 'VAULT_ADDR=https://vault.test-elvia.io' >> "$GITHUB_ENV"
        elif [[ "$ENVIRONMENT" == 'prod' ]]; then
          echo 'VAULT_ADDR=https://vault.elvia.io' >> "$GITHUB_ENV"
        else
          echo "Unsupported environment: $ENVIRONMENT"
          exit 1
        fi

        echo "REPO_SHORT_NAME=${GITHUB_REPOSITORY##*/}" >> "$GITHUB_ENV"
      env:
        ENVIRONMENT: ${{ inputs.environment }}

    - name: Login to Vault and export token
      uses: hashicorp/vault-action@4c06c5ccf5c0761b6029f56cfb1dcf5565918a3b # v3
      with:
        url: ${{ env.VAULT_ADDR }}
        role: 'jwt-github-${{ inputs.system }}-${{ env.REPO_SHORT_NAME }}'
        method: 'jwt'
        path: 'jwt-github'
        exportToken: ${{ inputs.exportToken }}
        secrets: |
          ${{ inputs.secrets }}

    - name: Show message on failure
      if: failure()
      shell: bash
      run: |
        # Show message on failure
        echo "::error::To access Vault, this repository must be added to https://github.com/3lvia/github-repositories-terraform/tree/trunk/systems"
        if [[ -z "$ACTIONS_ID_TOKEN_REQUEST_URL" ]]; then
          echo "::error::This action requires the permission 'id-token: write' to be added to the workflow."
          exit 1
        fi
        exit 1
