name: demo-api-go
namespace: core
microserviceType: webapi

replicaCount:
  dev: 1
  sandbox: 1
  test: 1
  prod: 1

env:
  - name: GIN_MODE
    value: 'release'

service:
  port: 80
  targetPort: 8080

ingress:
  subdomain: core
  path: '/demo-api-go'

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

readinessProbe:
  failureThreshold: 3
  httpGet:
    path: /status
    port: 8080
    scheme: HTTP
  initialDelaySeconds: 15
  periodSeconds: 15
  successThreshold: 1
  timeoutSeconds: 3

livenessProbe:
  failureThreshold: 5
  httpGet:
    path: /status
    port: 8080
    scheme: HTTP
  initialDelaySeconds: 15
  periodSeconds: 15
  successThreshold: 1
  timeoutSeconds: 3

startupProbe:
  failureThreshold: 30
  httpGet:
    path: /status
    port: 8080
    scheme: HTTP
  initialDelaySeconds: 15
  periodSeconds: 3
  successThreshold: 1
  timeoutSeconds: 2
