name: Check format of workflows

on:
  pull_request:
    branches: [trunk]
  push:
    branches: [trunk]

jobs:
  prettier_check:
    name: 'Prettier check'
    runs-on: ubuntu-latest
    if: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn global add prettier

      - name: Check format of workflows and README
        run: prettier -c --single-quote "**/*.yml" "**/*.md"
