name: Build and deploy .NET to Atlas ISS

on:
  push:
    branches: [too-complicated-to-setup-tests-for-this-so-we-dont]
##  Adding a path filter will only trigger the workflow if the files in the path are modified.
##  This is very useful if you have a monorepo structure.
##  See https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore for more information.
##
#    paths:
#     - 'applications/my-app/**'
##
#  pull_request:
#    branches: [trunk]

env:
  SYSTEM_NAME: 'iss'
  APPLICATION_NAME: 'demo-api'
  PROJECT_FILE: 'applications/demo-api/src/demo-api.csproj'
  HELM_VALUES_FILE: '.github/deploy/values-demo-api.yaml'

jobs:
  analyze:
    name: Analyze
    runs-on: elvia-runner
    permissions:
      actions: read
      contents: read
      security-events: write
    # Limits the number of concurrent runs of this job to one, and cancels any in progress.
    concurrency:
      group: '${{ github.workflow }}-${{ github.ref }}-analyze'
      cancel-in-progress: true
    steps:
      - uses: 3lvia/core-github-actions-templates/analyze@trunk
        with:
          # This can be set to a more specific path if you want to analyze only a part of the repository.
          working-directory: '.'
          language: 'csharp'

  unit-tests:
    name: Unit Tests
    runs-on: elvia-runner
    permissions:
      contents: read
      checks: write
      issues: read
      pull-requests: write
    # Limits the number of concurrent runs of this job to one, and cancels any in progress.
    concurrency:
      group: '${{ github.workflow }}-${{ github.ref }}-unit-tests'
      cancel-in-progress: true
    steps:
      - uses: 3lvia/core-github-actions-templates/unittest@trunk
        with:
          # This can be set to a more specific path if you want to search for tests in only a part of the repository.
          working-directory: '.'
          test-coverage: 'true'

  integration-tests:
    name: Integration Tests
    runs-on: elvia-runner
    permissions:
      contents: read
      checks: write
      issues: read
      pull-requests: write
      id-token: write
    # Limits the number of concurrent runs of this job to one, and cancels any in progress.
    concurrency:
      group: '${{ github.workflow }}-${{ github.ref }}-integration-tests'
      cancel-in-progress: true
    steps:
      - uses: 3lvia/core-github-actions-templates/integrationtest@trunk
        with:
          # This can be set to a more specific path if you want to search for tests in only a part of the repository.
          working-directory: '.'
          system: ${{ env.SYSTEM_NAME }}

  build:
    name: Build
    runs-on: elvia-runner
    permissions:
      actions: read
      contents: write
      id-token: write
      packages: write
      pull-requests: write
      security-events: write
    # Limits the number of concurrent runs of this job to one, and cancels any in progress.
    concurrency:
      group: '${{ github.workflow }}-${{ github.ref }}-build'
      cancel-in-progress: true
    outputs:
      image: ${{ steps.build.outputs.image-name-with-tag }}
    steps:
      - uses: 3lvia/core-github-actions-templates/build@trunk
        id: build
        with:
          name: ${{ env.APPLICATION_NAME }}
          namespace: ${{ env.SYSTEM_NAME }}
          project-file: ${{ env.PROJECT_FILE }}
          trivy-upload-report: 'true'
          trivy-post-comment: 'true'
          registry: 'ghcr.io/3lvia'

  push-images:
    name: Push images to GCR
    needs: [build]
    runs-on: 'iss-agent-vm-${{ matrix.environment }}-runner'
    permissions:
      contents: read
      packages: read
    strategy:
      matrix:
        environment:
          - dev
          - test
          - prod
    # Limits the number of concurrent runs of this job to one per matrix, but DOES NOT cancel any in progress.
    concurrency:
      group: '${{ github.workflow }}-${{ github.ref }}-${{ matrix.environment }}-push-images'
    environment: ${{ matrix.environment }}
    steps:
      - name: Tag image and push to GCR
        # On pull requests, only push to dev GCR
        if: ${{ github.ref == 'refs/heads/trunk' || (github.event_name == 'pull_request' && matrix.environment == 'dev') }}
        uses: 3lvia/core-github-actions-templates/iss-tag-push-image@trunk
        with:
          old-image-name-with-tag: ${{ needs.build.outputs.image }}
          new-image-name: 'gcr.io/${{ vars.GC_ISS_PROJECT_ID  }}/${{ env.SYSTEM_NAME }}-${{ env.APPLICATION_NAME }}'

  deploy-dev:
    name: Deploy Dev
    # Require all jobs below to be successful before running this job.
    # Any of these (except `push-images`) can be commented out or removed if you want to deploy anyway.
    needs:
      - analyze
      - unit-tests
      - integration-tests
      - push-images # Never remove this, as it is required for the deployment to work.
    runs-on: iss-agent-vm-dev-runner
    permissions:
      contents: read
      id-token: write
      packages: read
    # Limits the number of concurrent runs of this job to one, but DOES NOT cancel any in progress.
    concurrency:
      group: '${{ github.workflow }}-${{ github.ref }}-deploy-dev'
    environment: dev
    steps:
      - uses: 3lvia/core-github-actions-templates/deploy@trunk
        with:
          name: ${{ env.APPLICATION_NAME }}
          namespace: ${{ env.SYSTEM_NAME }}
          environment: 'dev'
          helm-values-file: ${{ env.HELM_VALUES_FILE }}
          runtime-cloud-provider: 'ISS'
          # Will post to the Slack channel of your system if the deployment fails.
          # Can be commented out if you don't want this.
          slack-channel: '#team-${{ env.SYSTEM_NAME }}-alerts'

  deploy-test:
    name: Deploy Test
    # Only deploy to test after dev
    needs: [deploy-dev]
    runs-on: iss-agent-vm-test-runner
    permissions:
      contents: read
      id-token: write
    # Limits the number of concurrent runs of this job to one, but DOES NOT cancel any in progress.
    concurrency:
      group: '${{ github.workflow }}-${{ github.ref }}-deploy-test'
    environment: test
    # Only on push to trunk
    if: github.ref == 'refs/heads/trunk'
    steps:
      - uses: 3lvia/core-github-actions-templates/deploy@trunk
        with:
          name: ${{ env.APPLICATION_NAME }}
          namespace: ${{ env.SYSTEM_NAME }}
          environment: 'test'
          helm-values-file: ${{ env.HELM_VALUES_FILE }}
          runtime-cloud-provider: 'ISS'
          # Will post to the Slack channel of your system if the deployment fails.
          # Can be commented out if you don't want this.
          slack-channel: '#team-${{ env.SYSTEM_NAME }}-alerts'

  deploy-prod:
    name: Deploy Prod
    # Only deploy to prod after test
    needs: [deploy-test]
    runs-on: iss-agent-vm-prod-runner
    permissions:
      contents: read
      id-token: write
    # Limits the number of concurrent runs of this job to one, but DOES NOT cancel any in progress.
    concurrency:
      group: '${{ github.workflow }}-${{ github.ref }}-deploy-prod'
    environment: prod
    # Only on push to trunk
    if: github.ref == 'refs/heads/trunk'
    steps:
      - uses: 3lvia/core-github-actions-templates/deploy@trunk
        with:
          name: ${{ env.APPLICATION_NAME }}
          namespace: ${{ env.SYSTEM_NAME }}
          environment: 'prod'
          helm-values-file: ${{ env.HELM_VALUES_FILE }}
          runtime-cloud-provider: 'ISS'
          # Will post to the Slack channel of your system if the deployment fails.
          # Can be commented out if you don't want this.
          slack-channel: '#team-${{ env.SYSTEM_NAME }}-alerts'


