name: Generate action documentation

on:
  push:
    branches: [trunk]
  pull_request: # TODO: remove
    branches: [trunk]

jobs:
  generate_docs:
    name: Generate action documentation
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Generate action documentation
        uses: ./internal/gh-actions-docs

      - name: Format README
        run: yarn prettier -w --single-quote README.md

      - name: Debug, remove this # TODO: remove
        run: cat README.md

      - name: Commit changes
        if: false
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add README.md
          git commit -m "Update action documentation"
          git push
