# Note that these annotations are not tied to a single dashboard, but are tagged with system, application, etc
# and dynamically added to matching panels. 

name: Add annotation to Grafana Cloud

on:
  workflow_call:
    inputs:
      title:
        description: 'The title of the annotation.'
        required: true
        type: string
      description:
        description: 'The full text of the annotation. '
        required: true
        type: string
      app:
        description: 'Application name'
        required: true
        type: string
      system:
        description: 'System name'
        required: true
        type: string
      env:
        description: 'Environment'
        required: true
        type: string
      event:
        description: 'Event type. For instance deploy'
        required: true
        type: string

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: 3lvia/core-github-actions-templates # the template repo
        path: template34122
      if: always()

    - name: Read secrets from vault
      uses: hashicorp/vault-action@v2
      with:
        url: https://vault.dev-elvia.io/
        role: jwt-github-${{input.system}}
        method: jwt
        path: jwt-github
        secrets: |
            monitoring/kv/shared grafana_api_url        | grafana_api_url
            monitoring/kv/shared grafana_editor_api_key | grafana_editor_api_key
    - name: Output
      run: |
        echo ${{env.grafana_api_url}} 
