name: Push Trivy Database Mirror

on:
  push:
    branches: [trunk]
    paths: ['.github/workflows/push-trivy-db-mirror.yml']
  pull_request:
    branches: [trunk]
    paths: ['.github/workflows/push-trivy-db-mirror.yml']
  schedule:
    # Run every 6 hours, which is when Trivy updates their database
    - cron: '45 */6 * * *'

jobs:
  push-trivy-db-mirror:
    name: Push Trivy Database Mirror
    runs-on: elvia-runner
    permissions:
      contents: read
      packages: write
    steps:
      - name: Login to GHCR
        run: |
          echo "$GITHUB_TOKEN" | oras login ghcr.io -u "$GITHUB_USERNAME" --password-stdin
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}

      - name: Pull Trivy Database Mirror
        run: oras pull ghcr.io/aquasecurity/trivy-db:2

      - name: Push Trivy Database Mirror
        run: |
          oras push \
            --artifact-type application/vnd.aquasec.trivy.config.v1+json \
            'ghcr.io/${{ github.repository_owner }}/trivy-db:2' \
            db.tar.gz:application/vnd.aquasec.trivy.db.layer.v1.tar+gzip
