name: Test actions

on:
  pull_request:
    branches: [trunk]

env:
  APPLICATION_NAME: 'demo-api'
  SYSTEM_NAMESPACE: 'core'

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: elvia-runner
    permissions:
      contents: read
      checks: write
      issues: read
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./unittest
        with:
          checkout: 'false'

  integration-tests:
    name: Integration Tests
    runs-on: elvia-runner
    permissions:
      contents: read
      checks: write
      issues: read
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./integrationtest
        with:
          checkout: 'false'
          system: ${{ env.SYSTEM_NAMESPACE }}

  analyze:
    name: Analyze
    runs-on: elvia-runner-dev
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./analyze
        with:
          checkout: 'false'

  build:
    name: Build
    runs-on: elvia-runner
    permissions:
      contents: read
      id-token: write
    environment: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./build
        with:
          checkout: 'false'
          name: ${{ env.APPLICATION_NAME }}
          namespace: ${{ env.SYSTEM_NAMESPACE }}
          dockerfile: '.github/test/src/Dockerfile'
          severity: 'CRITICAL'
          AZURE_CLIENT_ID: ${{ vars.ACR_CLIENT_ID }}

  deploy-dev:
    name: Deploy Dev
    needs: [build]
    runs-on: elvia-runner
    permissions:
      contents: read
      id-token: write
    environment: dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./deploy
        with:
          checkout: 'false'
          name: ${{ env.APPLICATION_NAME }}
          namespace: ${{ env.SYSTEM_NAMESPACE }}
          environment: 'dev'
          helm-values-path: '.github/test/deploy/values.yml'
          AZURE_CLIENT_ID: ${{ vars.AKS_CLIENT_ID }}

  deploy-dev-gke:
    name: Deploy Dev GKE
    needs: [build]
    runs-on: elvia-runner
    permissions:
      contents: read
      id-token: write
    environment: dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./deploy
        with:
          checkout: 'false'
          name: ${{ env.APPLICATION_NAME }}
          namespace: ${{ env.SYSTEM_NAMESPACE }}
          environment: 'dev'
          helm-values-path: '.github/test/deploy/values.yml'
          runtime-cloud-provider: 'GKE'
          GC_SERVICE_ACCOUNT: ${{ vars.GC_SERVICE_ACCOUNT }}
          GC_WORKLOAD_IDENTITY_PROVIDER: ${{ vars.GC_WORKLOAD_IDENTITY_PROVIDER }}

  trivy-iac-scan:
    name: Trivy IaC Scan
    runs-on: elvia-runner
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./trivy-iac-scan
        with:
          checkout: 'false'

  terraform-format-check:
    name: Terraform Format Check
    runs-on: elvia-runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./terraform-format
        with:
          checkout: 'false'
