name: Verify action pinning policy

on:
  pull_request:
  merge_group:
  push:
    branches:
      - main
      - master
      - trunk

permissions:
  contents: read

jobs:
  verify:
    name: verify-action-pinning
    runs-on: ubuntu-latest

    steps:
      - name: Check out target repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Check out policy scripts
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          repository: '3lvia/core-github-actions-templates'
          path: '.policy-tools'

      - name: Validate workflows
        run: python3 .policy-tools/.github/scripts/verify_action_pinning.py
